### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by Aperrix** [drdevelop/typescript-module-alias#2]
Hi everyone 👋  ! 

I have an error that I can't explain, anyone have an idea?

# ERROR
![image](https://user-images.githubusercontent.com/26674548/102010108-34e9c600-3d3c-11eb-8154-d910416a0db7.png)

# COMMAND
```bash
"dev": "typescript-module-alias src/dev.ts > console.log",
```

# TSCONFIG
```json
{
    "compileOnSave": true,
    "compilerOptions": {
        "target": "ESNext",
        "module": "CommonJS",
        "lib": ["ESNext"],
        "allowJs": true,
        "checkJs": true,
        "declaration": true,
        "declarationMap": true,
        "sourceMap": true,
        "outDir": "lib",
        "rootDir": "src",
        "removeComments": true,
        "importHelpers": true,
        "downlevelIteration": true,
        "strict": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "strictBindCallApply": true,
        "strictPropertyInitialization": true,
        "noImplicitThis": true,
        "alwaysStrict": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "forceConsistentCasingInFileNames": true,
        "moduleResolution": "node",
        "esModuleInterop": true,
        "resolveJsonModule": true,
        "baseUrl": "./",
        "paths": {
            "@root/*": ["./src/*"],
            "@configs/*": ["./src/configs/*"],
            "@schemas/*": ["./src/schemas/*"],
            "@modules/*": ["./src/modules/*"],
            "@tools/*": ["./src/tools/*"]
        }
    },
    "include": ["src/**/*.ts"],
    "exclude": ["src/dev.ts", "node_modules", "lib", "**/__tests__/*"]
}
```

**Comment by drdevelop** [comment]
> Hi everyone 👋 !
> 
> I have an error that I can't explain, anyone have an idea?
> 
> # ERROR
> ![image](https://user-images.githubusercontent.com/26674548/102010108-34e9c600-3d3c-11eb-8154-d910416a0db7.png)
> 
> # COMMAND
> ```shell
> "dev": "typescript-module-alias src/dev.ts > console.log",
> ```
> 
> # TSCONFIG
> ```json
> {
>     "compileOnSave": true,
>     "compilerOptions": {
>         "target": "ESNext",
>         "module": "CommonJS",
>         "lib": ["ESNext"],
>         "allowJs": true,
>         "checkJs": true,
>         "declaration": true,
>         "declarationMap": true,
>         "sourceMap": true,
>         "outDir": "lib",
>         "rootDir": "src",
>         "removeComments": true,
>         "importHelpers": true,
>         "downlevelIteration": true,
>         "strict": true,
>         "noImplicitAny": true,
>         "strictNullChecks": true,
>         "strictFunctionTypes": true,
>         "strictBindCallApply": true,
>         "strictPropertyInitialization": true,
>         "noImplicitThis": true,
>         "alwaysStrict": true,
>         "noUnusedLocals": true,
>         "noUnusedParameters": true,
>         "noImplicitReturns": true,
>         "noFallthroughCasesInSwitch": true,
>         "forceConsistentCasingInFileNames": true,
>         "moduleResolution": "node",
>         "esModuleInterop": true,
>         "resolveJsonModule": true,
>         "baseUrl": "./",
>         "paths": {
>             "@root/*": ["./src/*"],
>             "@configs/*": ["./src/configs/*"],
>             "@schemas/*": ["./src/schemas/*"],
>             "@modules/*": ["./src/modules/*"],
>             "@tools/*": ["./src/tools/*"]
>         }
>     },
>     "include": ["src/**/*.ts"],
>     "exclude": ["src/dev.ts", "node_modules", "lib", "**/__tests__/*"]
> }
> ```

you can try [v2.1.0](https://www.npmjs.com/package/typescript-module-alias/v/2.1.0)

**Comment by drdevelop** [comment]
Execiting!!! The version v2.1.0 provide build command. For example, the script command is "typescript-module-alias-build ./src --out-dir release"

**Comment by drdevelop** [comment]
can't reproduce
