### ISSUE TITLE
how to use with nodemon

### ISSUE THREAD

**Issue by robbiemu** [drdevelop/typescript-module-alias#3]
How can we use this with a runtime changes monitor script like the popular nodemon?

**Comment by drdevelop** [comment]
> How can we use this with a runtime changes monitor script like the popular nodemon?

you can try [v2.1.0](https://www.npmjs.com/package/typescript-module-alias/v/2.1.0)，then run nodemon --exec xxx. For example, the script command is "nodemon --exec typescript-module-alias ./src/a/index.ts".
