### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by Majoramari** [drdevelop/typescript-module-alias#4]
Getting this error `The system cannot find the path specified` 

this si my tsconfig.json
```ts
{
  "include": ["src/**/*.ts"],
  "compilerOptions": {
    "module": "CommonJS",
    "target": "ES5",
    "moduleResolution": "node",
    "rootDir": "src",
    "outDir": "build",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "useDefineForClassFields": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "resolveJsonModule": true,
    "strict": true,
    "noImplicitAny": false,
    "importHelpers": true,
    "newLine": "lf",
    "noEmitHelpers": true,
    "preserveConstEnums": true,
    "removeComments": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": "src",
    "paths": {
      "@config/*": ["assets/config/*"]
    }
  }
}

```

and this is my execute command: nodemon --exec typescript-module-alias src/bot.ts

**Comment by drdevelop** [comment]
@Majoramari what's your version about typescript-module-alias?

**Comment by drdevelop** [comment]
@Majoramari When use your config and command,  i try the newest version is working normal.

**Comment by Majoramari** [comment]
> @Majoramari When use your config and command, i try the newest version is working normal.

Isn't 2.1.0 the latest version?

I'm still getting this error
![image](https://user-images.githubusercontent.com/33487552/176606850-c4897e14-74b3-44f3-be25-0fdbbaa75256.png)

**Comment by drdevelop** [comment]
@Majoramari Are you using window system?

**Comment by Majoramari** [comment]
> @Majoramari Are you using window system?

Yeah using windows 10, nodejs 18

**Comment by drdevelop** [comment]
@Majoramari Sorry, It may not be compatible with windows, i will fix it as soon as possible.

**Comment by drdevelop** [comment]
@Majoramari try the version 2.2.1.

**Comment by Majoramari** [comment]
tried the same command: `nodemon --exec typescript-module-alias src/bot.ts` and `npx typescript-module-alias src/bot.ts` at version 2.2.1 both gave me same error this:

```
Command failed: npx babel-node --extensions .ts,.js C:\Users\Major\Documents\github\Sitrum\src\bot.ts --config-file C:\Users\Major\Documents\github\Sitrum\node_modules\.pnpm\typescript-module-alias@2.2.1_typescript@4.7.4\node_modules\typescript-module-alias\babel.config.js
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Major\AppData\Local\npm-cache\_logs\2022-07-02T17_12_59_369Z-debug-0.log
```

this is the log file mentioned above: [2022-07-02T17_12_59_369Z-debug-0.log](https://github.com/drdevelop/typescript-module-alias/files/9033366/2022-07-02T17_12_59_369Z-debug-0.log)

**Comment by drdevelop** [comment]
I found out that this is caused by the mechanism by which pnpm installs dependent packages.

**Comment by drdevelop** [comment]
"peerDependencies": {
    "@babel/cli": ">=7.0.0",
    "@babel/core": ">=7.0.0",
    "@babel/node": ">=7.0.0",
    "typescript": ">=1.0.0"
  }

**Comment by Majoramari** [comment]
> "peerDependencies": { "@babel/core": ">=7.0.0", "@babel/node": ">=7.0.0", "typescript": ">=1.0.0" }

Notes just to be clear:
typescript version: 
I've tried yarn, npm and pnpm!

I've added the following fields to `package.json` when I try to use it it just stuck like this:
![image](https://live.staticflickr.com/65535/52190155943_089a91bf04_o.gif)

I waited 15 min

**Comment by drdevelop** [comment]
@Majoramari First, upgrade to v2.2.6. Next, exec the command "pnpm add @babel/cli@^7.0.0 @babel/core@^7.0.0 @babel/node@^7.0.0 -D". Try it.

**Comment by drdevelop** [comment]
i just tried above steps in the window system, it run successful!

**Comment by drdevelop** [comment]
> 

That's because  I didn't output the user's log to the console in the previous version.

**Comment by Majoramari** [comment]
> @Majoramari First, upgrade to v2.2.6. Next, exec the command "pnpm add @babel/cli@^7.0.0 @babel/core@^7.0.0 @babel/node@^7.0.0 -D". Try it.

Received this error:
```
TypeError [ERR_INVALID_ARG_TYPE]: [BABEL]: The "path" argument must be of type string. Received undefined (While processing:
```
This is a [demo](https://github.com/drdevelop/typescript-module-alias/files/9034706/demo.zip) project I used to test the module

**Comment by drdevelop** [comment]
@Majoramari compilerOptions.baseUrl is required in tsconfig.json file

**Comment by drdevelop** [comment]
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/39514265/177043770-59622631-2cc3-4bda-b40a-a3a6e9f3ac20.png">

**Comment by drdevelop** [comment]
@Majoramari you can also upgrade to the latest version 2.2.7. This version sets './' as default baseUrl

**Comment by Majoramari** [comment]
> @Majoramari you can also upgrade to the latest version 2.2.7. This version sets './' as default baseUrl

That's weird, it's working fine in the demo and showing up outputs, but in my main app seems to resolve the paths fine but no output from the app (no console log showing up):
![image](https://live.staticflickr.com/65535/52190734523_e38eaf8ce4_o.gif)

this is my current tsconfig.json:
```json
{
  "include": ["src/**/*.ts"],
  "compilerOptions": {
    "module": "CommonJS",
    "target": "ES2020",
    "moduleResolution": "node",
    "rootDir": "src",
    "outDir": "build",
    "allowUnreachableCode": false,
    "resolveJsonModule": true,
    "strict": true,
    "noImplicitAny": false,
    "removeComments": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": "src",
    "paths": {
      "@sitrum/client": ["structure/SitrumClient.ts"],
      "@sitrum/player": ["structure/SitrumPlayer.ts"],
      "@sitrum/CommandManager": ["helpers/Command/CommandManager.ts"],
      "@sitrum/types": ["helpers/utils/types/index.ts"],
      "@sitrum/config": ["assets/config/settings.json"],
      "@sitrum/base": ["structure/base/index.ts"],
      "@sitrum/helper": ["helpers/index.ts"]
    }
  }
}
```

**Comment by drdevelop** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/39514265/177063412-f3bf1eaf-8bf3-4796-b89f-6946727804cc.png">
here is entry, you can debug it.

**Comment by drdevelop** [comment]
I will use spawn instead of exec to create child process, it maybe can output console

**Comment by Majoramari** [comment]
> I will use spawn instead of exec to create child process, it maybe can output console

Yeah, looks like we need to switch to spawn but as far as I know spawn doesn't work on Windows

**Comment by drdevelop** [comment]
> > I will use spawn instead of exec to create child process, it maybe can output console
> 
> Yeah, looks like we need to switch to spawn but as far as I know spawn doesn't work on Windows

Compatible with window systems when setting option "shell: true"

**Comment by drdevelop** [comment]
> > @Majoramari you can also upgrade to the latest version 2.2.7. This version sets './' as default baseUrl
> 
> That's weird, it's working fine in the demo and showing up outputs, but in my main app seems to resolve the paths fine but no output from the app (no console log showing up): ![image](https://camo.githubusercontent.com/ab4b7e8f079839f775ec7ae2ef076068e41d672fea184357f8b8f50cf6fb07ea/68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f35323139303733343532335f653338656166386365345f6f2e676966) [ ](https://camo.githubusercontent.com/ab4b7e8f079839f775ec7ae2ef076068e41d672fea184357f8b8f50cf6fb07ea/68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f35323139303733343532335f653338656166386365345f6f2e676966) ![image](https://camo.githubusercontent.com/ab4b7e8f079839f775ec7ae2ef076068e41d672fea184357f8b8f50cf6fb07ea/68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f35323139303733343532335f653338656166386365345f6f2e676966) [ ](https://camo.githubusercontent.com/ab4b7e8f079839f775ec7ae2ef076068e41d672fea184357f8b8f50cf6fb07ea/68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f35323139303733343532335f653338656166386365345f6f2e676966)
> 
> this is my current tsconfig.json:
> 
> ```json
> {
>   "include": ["src/**/*.ts"],
>   "compilerOptions": {
>     "module": "CommonJS",
>     "target": "ES2020",
>     "moduleResolution": "node",
>     "rootDir": "src",
>     "outDir": "build",
>     "allowUnreachableCode": false,
>     "resolveJsonModule": true,
>     "strict": true,
>     "noImplicitAny": false,
>     "removeComments": true,
>     "esModuleInterop": true,
>     "forceConsistentCasingInFileNames": true,
>     "baseUrl": "src",
>     "paths": {
>       "@sitrum/client": ["structure/SitrumClient.ts"],
>       "@sitrum/player": ["structure/SitrumPlayer.ts"],
>       "@sitrum/CommandManager": ["helpers/Command/CommandManager.ts"],
>       "@sitrum/types": ["helpers/utils/types/index.ts"],
>       "@sitrum/config": ["assets/config/settings.json"],
>       "@sitrum/base": ["structure/base/index.ts"],
>       "@sitrum/helper": ["helpers/index.ts"]
>     }
>   }
> }
> ```

@Majoramari Try version 2.2.8

**Comment by Majoramari** [comment]
> @Majoramari Try version 2.2.8

Yeah, that version works fine!!! Thanks

**Comment by drdevelop** [comment]
> > @Majoramari Try version 2.2.8
> 
> Yeah, that version works fine!!! Thanks

Good!
